runtime: nodejs14 

env: standard 
handlers:
  - url: /.*
    script: auto

env_variables:
  DB_HOST: '34.57.56.122' 
  DB_USER: 'root' 
  DB_PASSWORD: 'Yr}OO7.rpQO7vPV#' 
  DB_NAME: 'FridgeRecipe' 
  GCLOUD_PROJECT_ID: 'fridgerecipe-442714'
  GCLOUD_KEYFILE: './keys.json'
  GCLOUD_BUCKET_NAME: 'fridge-recipe'
  JWT_SECRET: '099051a2ef41ab45fa86987690754feff13add4c580773074619cda481d65eb0'
  SPOONACULAR_API_KEY: '4ad49a33f1af457b90624baa74efbaed'
